[project]
name = "browser_agent"
version = "0.1.0"
description = "This is an agent that will leverage a browser to research a company and prepare a competitor analysis report."
authors = [
    {name = "Lachlan Fergusson",email = "lachlan@fergusson.me"}
]
license = {text = "n"}
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "agent-framework (>=1.0.0b251007,<2.0.0)",
    "fastapi (>=0.119.0,<0.120.0)"
]

[[tool.poetry.packages]]
include = "code"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
